#
#   docker-image-server.yml - push the server docker image in dockerhub
# 
#   Programma sviluppato come parte del progetto su Docker
#   per il corso di SSGS dell'Universiota' degli Studi di Genova 
#
#   Copyright (C) <2023>  Andrea Valenzano 4548315
#   Copyright (C) <2023>  Nicola Incardona 4750770
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

name: SSGS Labo Server

on:
  push:
    branches:
      - "main"

jobs:
  push_to_registry:
    name: Build/Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./docker_images/server
          file: ./docker_images/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ssgs_labo_docker_server:latest

